[dev]
  framework = "#static"

[build]
  command = "echo No build for this app"
  publich = "public"

[[edge_functions]]
  path = "/track"
  function = "track"

[[edge_functions]]
  path = "/tracker.js"
  function = "tracker"

[[edge_functions]]
  path = "/*"
  function = "splitHandler"

[functions]
deno_import_map = "./import_map.json"
